# Site settings
title: Nicolas Senet-Larson
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://NicolasSenet-Larson.github.io" # the base hostname & protocol for your site, e.g. http://example.com
favicon: arngrim-favicon.png
description: >
    Developer - Engineer - Designer

# Date
date_format: "%Y"

# Homepage
logo: arngrim-circle.svg
catchphrase: Developer - Engineer - Designer

# Networking
social:
    -
        title:  RSS
        icon:   rss.svg
        url:    /feed.xml
    -
        title:  Email
        icon:   mail.svg
        url:    mailto:nico.senetlarson@btinternet.com
    -
        title:  Github
        icon:   github.svg
        url:    https://github.com/NicolasSenet-Larson
    -
        title:  Linkedin
        icon:   linkedin.svg
        url:    https://www.linkedin.com/in/nicolas-senet-larson
    -
        title:  Facebook
        icon:   facebook.svg
        url:
    -
        title:  Deviantart
        icon:   deviantart.svg
        url:    https://dinodig2010.deviantart.com

# Footer note
notice: Copyright Â© 2017 <a href="https://NicolasSenet-Larson.github.io">Nicolas Senet-Larson</a>.
    Powered by <a href="https://jekyllrb.com/">Jekyll</a>.
    Icons theme by <a href="https://numixproject.org/">Numix</a>.

# Build settings
markdown: kramdown
permalink: /:year/:title/
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
